# Relatório de Análise I

## Importando a Base de Dados

In [3]:
import pandas as pd

In [5]:
pd.read_csv('aluguel.csv', sep =';')

              Tipo               Bairro  Quartos  ...   IPTU  Valor m2  Tipo Agregado
0      Apartamento               Centro        1  ...   20.0     53.33    Apartamento
1      Apartamento         Higienópolis        1  ...    0.0     16.67    Apartamento
2      Apartamento             Cachambi        2  ...   17.0     26.00    Apartamento
3      Apartamento               Grajaú        2  ...   74.0     21.43    Apartamento
4      Apartamento  Lins de Vasconcelos        3  ...   14.0     16.67    Apartamento
...            ...                  ...      ...  ...    ...       ...            ...
19826    Quitinete               Glória        1  ...   10.0     40.00    Apartamento
19827    Quitinete             Flamengo        1  ...    0.0     39.13    Apartamento
19828    Quitinete               Centro        1  ...    0.0     45.83    Apartamento
19829    Quitinete           Copacabana        1  ...  200.0     68.18    Apartamento
19830    Quitinete               Centro        0  ...   25.0     29.63    Apartamento

[19831 rows x 11 columns]

In [6]:
dados = pd.read_csv('aluguel.csv', sep =';')

In [7]:
dados

              Tipo               Bairro  Quartos  ...   IPTU  Valor m2  Tipo Agregado
0      Apartamento               Centro        1  ...   20.0     53.33    Apartamento
1      Apartamento         Higienópolis        1  ...    0.0     16.67    Apartamento
2      Apartamento             Cachambi        2  ...   17.0     26.00    Apartamento
3      Apartamento               Grajaú        2  ...   74.0     21.43    Apartamento
4      Apartamento  Lins de Vasconcelos        3  ...   14.0     16.67    Apartamento
...            ...                  ...      ...  ...    ...       ...            ...
19826    Quitinete               Glória        1  ...   10.0     40.00    Apartamento
19827    Quitinete             Flamengo        1  ...    0.0     39.13    Apartamento
19828    Quitinete               Centro        1  ...    0.0     45.83    Apartamento
19829    Quitinete           Copacabana        1  ...  200.0     68.18    Apartamento
19830    Quitinete               Centro        0  ...   25.0     29.63    Apartamento

[19831 rows x 11 columns]

In [8]:
type(dados)

pandas.core.frame.DataFrame

In [10]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19831 entries, 0 to 19830
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tipo           19831 non-null  object
 1   Bairro         19831 non-null  object
 2   Quartos        19831 non-null  int64
 3   Vagas          19831 non-null  int64
 4   Suites         19831 non-null  int64
 5   Area           19831 non-null  int64
 6   Valor          19831 non-null  float64
 7   Condominio     19831 non-null  float64
 8   IPTU           19831 non-null  float64
 9   Valor m2       19831 non-null  float64
 10  Tipo Agregado  19831 non-null  object
dtypes: float64(4), int64(4), object(3)
memory usage: 1.7+ MB

In [12]:
dados.head(10) #mdefine o número de linhas a ser visualizado

          Tipo                   Bairro  Quartos  ...   IPTU  Valor m2  Tipo Agregado
0  Apartamento                   Centro        1  ...   20.0     53.33    Apartamento
1  Apartamento             Higienópolis        1  ...    0.0     16.67    Apartamento
2  Apartamento                 Cachambi        2  ...   17.0     26.00    Apartamento
3  Apartamento                   Grajaú        2  ...   74.0     21.43    Apartamento
4  Apartamento      Lins de Vasconcelos        3  ...   14.0     16.67    Apartamento
5  Apartamento               Copacabana        1  ...   50.0     50.00    Apartamento
6  Apartamento  Freguesia (Jacarepaguá)        3  ...   28.0     17.59    Apartamento
7  Apartamento          Barra da Tijuca        2  ...  147.0     25.37    Apartamento
8  Apartamento                   Tijuca        2  ...  138.0     17.27    Apartamento
9  Apartamento                   Olaria        3  ...    0.0     14.71    Apartamento

[10 rows x 11 columns]

## Informações Gerais sobre a base de dados

In [13]:
dados.dtypes #mostra as variáveis e os tipos que els são.

Tipo              object
Bairro            object
Quartos            int64
Vagas              int64
Suites             int64
Area               int64
Valor            float64
Condominio       float64
IPTU             float64
Valor m2         float64
Tipo Agregado     object
dtype: object

In [23]:
tipos_de_dados = pd.DataFrame(dados.dtypes, columns = ['Tipos de Dados']) #mostrando na forma de data frame

In [17]:
tipos_de_dados.columns.name = "Variáveis" #nome da parte de index

In [18]:
tipos_de_dados

Variáveis     Tipos de Dados
Tipo                  object
Bairro                object
Quartos                int64
Vagas                  int64
Suites                 int64
Area                   int64
Valor                float64
Condominio           float64
IPTU                 float64
Valor m2             float64
Tipo Agregado         object

In [19]:
dados.shape #retorna (linhas, colunas) colunas = variaveis

(19831, 11)

In [21]:
print('A base de dados apresenta {} registro (imóveis) e {} variáveis'.format(dados.shape[0], dados.shape[1]))

A base de dados apresenta 19831 registro (imóveis) e 11 variáveis