#Relatório Análise V

In [75]:
import pandas as pd

In [76]:
dados = pd.read_csv('aluguel_residencial.csv', sep = ";")

In [77]:
dados.head(10)

                 Tipo           Bairro  Quartos  ...    Valor  Condominio  IPTU
0           Quitinete       Copacabana        1  ...   1700.0       500.0  60.0
1                Casa  Jardim Botânico        2  ...   7000.0         NaN   NaN
2         Apartamento           Centro        1  ...    800.0       390.0  20.0
3         Apartamento     Higienópolis        1  ...    800.0       230.0   NaN
4         Apartamento     Vista Alegre        3  ...   1200.0         NaN   NaN
5         Apartamento         Cachambi        2  ...   1300.0       301.0  17.0
6  Casa de Condomínio  Barra da Tijuca        5  ...  22000.0         NaN   NaN
7  Casa de Condomínio            Ramos        2  ...   1000.0         NaN   NaN
8         Apartamento           Centro        1  ...   1200.0         NaN   NaN
9         Apartamento           Grajaú        2  ...   1500.0       642.0  74.0

[10 rows x 9 columns]

In [78]:
dados.isnull()

        Tipo  Bairro  Quartos  Vagas  Suites   Area  Valor  Condominio   IPTU
0      False   False    False  False   False  False  False       False  False
1      False   False    False  False   False  False  False        True   True
2      False   False    False  False   False  False  False       False  False
3      False   False    False  False   False  False  False       False   True
4      False   False    False  False   False  False  False        True   True
...      ...     ...      ...    ...     ...    ...    ...         ...    ...
22575  False   False    False  False   False  False  False       False  False
22576  False   False    False  False   False  False  False       False  False
22577  False   False    False  False   False  False  False       False  False
22578  False   False    False  False   False  False  False       False  False
22579  False   False    False  False   False  False  False       False   True

[22580 rows x 9 columns]

In [79]:
dados.notnull()

       Tipo  Bairro  Quartos  Vagas  Suites  Area  Valor  Condominio   IPTU
0      True    True     True   True    True  True   True        True   True
1      True    True     True   True    True  True   True       False  False
2      True    True     True   True    True  True   True        True   True
3      True    True     True   True    True  True   True        True  False
4      True    True     True   True    True  True   True       False  False
...     ...     ...      ...    ...     ...   ...    ...         ...    ...
22575  True    True     True   True    True  True   True        True   True
22576  True    True     True   True    True  True   True        True   True
22577  True    True     True   True    True  True   True        True   True
22578  True    True     True   True    True  True   True        True   True
22579  True    True     True   True    True  True   True        True  False

[22580 rows x 9 columns]

In [80]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22580 entries, 0 to 22579
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        22580 non-null  object
 1   Bairro      22580 non-null  object
 2   Quartos     22580 non-null  int64
 3   Vagas       22580 non-null  int64
 4   Suites      22580 non-null  int64
 5   Area        22580 non-null  int64
 6   Valor       22571 non-null  float64
 7   Condominio  20765 non-null  float64
 8   IPTU        15795 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.6+ MB

In [81]:
dados["Valor"].isnull() #seleção de valores null cria uma series

0        False
1        False
2        False
3        False
4        False
         ...
22575    False
22576    False
22577    False
22578    False
22579    False
Name: Valor, Length: 22580, dtype: bool

In [82]:
dados[dados["Valor"].isnull()]

             Tipo           Bairro  Quartos  ...  Valor  Condominio   IPTU
58    Apartamento  Barra da Tijuca        2  ...    NaN       970.0   68.0
1492  Apartamento             Leme        2  ...    NaN       878.0    NaN
1683         Casa     Campo Grande        3  ...    NaN         NaN    NaN
2012  Apartamento         Botafogo        2  ...    NaN      1010.0  170.0
2034  Apartamento       Copacabana        2  ...    NaN       850.0    NaN
4941         Casa     Campo Grande        3  ...    NaN         NaN    NaN
8568  Apartamento             Leme        2  ...    NaN       878.0    NaN
8947  Apartamento           Glória        3  ...    NaN       910.0  228.0
9149  Apartamento            Gávea        3  ...    NaN       880.0  221.0

[9 rows x 9 columns]

In [83]:
dados[dados["Valor"].isnull()].shape[0]

9

In [84]:
A = dados.shape[0]
dados.dropna(subset = ["Valor"], inplace=True)
B = dados.shape[0]
A-B

9

## Tratamento de dados faltantes

In [85]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22571 entries, 0 to 22579
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        22571 non-null  object
 1   Bairro      22571 non-null  object
 2   Quartos     22571 non-null  int64
 3   Vagas       22571 non-null  int64
 4   Suites      22571 non-null  int64
 5   Area        22571 non-null  int64
 6   Valor       22571 non-null  float64
 7   Condominio  20758 non-null  float64
 8   IPTU        15791 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.7+ MB

In [86]:
dados[dados['Condominio'].isnull()].shape[0]

1813

In [87]:
selecao = (dados['Tipo'] == 'Apartamento') & (dados['Condominio'].isnull())

In [88]:
A = dados.shape[0]
dados = dados[~selecao]
B = dados.shape[0]
A-B

745

In [89]:
dados[dados['Condominio'].isnull()].shape[0]

1068

In [90]:
dados = dados.fillna({'Condominio':0, 'IPTU':0})

In [91]:
dados[dados['Condominio'].isnull()].shape[0]

0

In [92]:
dados[dados['IPTU'].isnull()].shape[0]

0

In [93]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21826 entries, 0 to 22579
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        21826 non-null  object
 1   Bairro      21826 non-null  object
 2   Quartos     21826 non-null  int64
 3   Vagas       21826 non-null  int64
 4   Suites      21826 non-null  int64
 5   Area        21826 non-null  int64
 6   Valor       21826 non-null  float64
 7   Condominio  21826 non-null  float64
 8   IPTU        21826 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.7+ MB

In [94]:
dados.to_csv('aluguel_residencial.csv', sep = ";")